#!/usr/bin/env node
/**
 * Generate the parts of the docs that describe machine-readable state.
 *
 * Every hand-maintained list in this repo's docs had gone stale: the README
 * named seven skills the installer does not install, claimed both installers
 * ship "the same skill set" (false since `targets:`), and pointed at a
 * statusline script that had been renamed. AGENTS.md is a hand-kept twin of
 * CLAUDE.md and had drifted the same way.
 *
 * So: prose that explains *intent* stays hand-written. Anything that states a
 * *fact about the repo* is generated from the repo.
 *
 *   node scripts/build-docs.mjs [--check]
 *
 * --check  exit 1 if any generated block is out of date (for CI / pre-push)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { REPO, readAllSkills, readExternalSkills } from './lib/skills.mjs';

const check = process.argv.includes('--check');

const HARNESSES = ['claude', 'cursor', 'codex'];

const skills = readAllSkills();
const external = readExternalSkills();

// ---------------------------------------------------------------------------
// Managed blocks
// ---------------------------------------------------------------------------

/**
 * Replace the content between the begin/end markers. The markers stay in the
 * file, so a reader editing by hand can see the edit will be overwritten.
 */
function applyBlock(text, id, body) {
  const begin = `<!-- generated:begin ${id} -->`;
  const end = `<!-- generated:end ${id} -->`;
  const from = text.indexOf(begin);
  const to = text.indexOf(end);
  if (from === -1 || to === -1) {
    console.error(`Missing "${begin}" / "${end}" markers.`);
    process.exit(2);
  }
  return `${text.slice(0, from + begin.length)}\n${body}\n${text.slice(to)}`;
}

const NOTE = '<!-- Generated by scripts/build-docs.mjs. Edits here are overwritten. -->';

// Mirrored into AGENTS.md alongside the skill-trigger sections. Matched on the
// heading prefix so the parenthetical can be reworded without breaking the build.
const ALSO_MIRRORED = '# Known Gotchas';

// ---------------------------------------------------------------------------
// README: the skill inventory
// ---------------------------------------------------------------------------

function buildInventory() {
  const counts = HARNESSES.map((h) => `${skills.filter((s) => s.targets.includes(h)).length} → ${h}`);
  const cursorOnly = skills.filter((s) => s.targets.length === 1 && s.targets[0] === 'cursor');
  const everywhere = skills.filter((s) => HARNESSES.every((h) => s.targets.includes(h)));
  const other = skills.filter((s) => !cursorOnly.includes(s) && !everywhere.includes(s));

  const lines = [
    NOTE,
    '',
    `**${skills.length} skills authored here.** Each declares its own targets: ${counts.join(', ')}.`,
    '',
    `### Everywhere (${everywhere.length})`,
    '',
    everywhere.map((s) => `\`${s.name}\``).join(' · '),
    '',
    `### Cursor only (${cursorOnly.length})`,
    '',
    'Claude receives richer vendored equivalents from upstream (below); Cursor has no',
    'vendoring mechanism, so these are its only coverage.',
    '',
    cursorOnly.map((s) => `\`${s.name}\``).join(' · '),
  ];

  if (other.length) {
    lines.push('', `### Other target combinations (${other.length})`, '');
    lines.push(other.map((s) => `\`${s.name}\` (${s.targets.join(', ')})`).join(' · '));
  }

  lines.push('', `### Vendored from upstream (${external.length}, Claude only)`, '');
  lines.push('Cloned by `install-claude.sh`. Skip them with `--skip-external`.', '');
  const byRepo = new Map();
  for (const e of external) {
    if (!byRepo.has(e.repo)) byRepo.set(e.repo, []);
    byRepo.get(e.repo).push(e.name);
  }
  for (const [repo, names] of [...byRepo].sort()) {
    lines.push(`- **${repo}** — ${names.map((n) => `\`${n}\``).join(', ')}`);
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// AGENTS.md: mirror CLAUDE.md's skill-trigger sections
// ---------------------------------------------------------------------------

/**
 * Every top-level section of CLAUDE.md that references a skill path is a
 * trigger section by construction, so the mirror cannot miss one that gets
 * added later — which is exactly how the previous hand-kept twin fell behind.
 */
function buildTriggers() {
  const text = readFileSync(join(REPO, 'CLAUDE.md'), 'utf8').split('\r\n').join('\n');
  const sections = text
    .split(/\n(?=# )/)
    // `skills/` marks a skill-trigger section. Known Gotchas is not one, but it
    // is harness-agnostic knowledge — Windows homedir, CRLF, Prisma, NestJS —
    // and Codex and Cursor have no other channel for it, since only Claude gets
    // the CLAUDE.md merge. It lived under an unrelated `# ` heading for years
    // and was excluded by accident rather than by judgement.
    .filter((s) => s.startsWith('# ') && (s.includes('skills/') || s.startsWith(ALSO_MIRRORED)))
    // The trailing `## ` sections of CLAUDE.md (tech stack, ports, gotchas) hang
    // off the last `# ` heading, so an untrimmed split drags all of them in and
    // makes this file a near-copy of the one it points at.
    .map((s) => s.split(/\n(?=## )/)[0].trim());
  return [NOTE, ...sections].join('\n\n');
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

const triggers = buildTriggers();
const edits = [
  { file: 'README.md', id: 'skills', body: buildInventory() },
  { file: 'AGENTS.md', id: 'triggers', body: triggers },
  { file: 'codex/AGENTS.md', id: 'triggers', body: triggers },
];

let stale = 0;
for (const { file, id, body } of edits) {
  const path = join(REPO, file);
  const before = readFileSync(path, 'utf8');
  // Compare on \n so a CRLF checkout does not report every file as stale.
  const after = applyBlock(before.split('\r\n').join('\n'), id, body);
  if (after === before.split('\r\n').join('\n')) {
    console.log(`  [ok] ${file} (${id})`);
    continue;
  }
  stale += 1;
  if (check) {
    console.error(`  [stale] ${file} (${id})`);
  } else {
    writeFileSync(path, after);
    console.log(`  [updated] ${file} (${id})`);
  }
}

if (check && stale) {
  console.error(`\n${stale} generated block(s) out of date. Run: node scripts/build-docs.mjs`);
  process.exit(1);
}
console.log(stale ? `\nUpdated ${stale} block(s).` : '\nDocs are up to date.');
